### ISSUE TITLE
Failed to resolve: io.ashdavies.rx.tasks:1.0.0

### ISSUE THREAD

**Issue by mradzinski** [ashdavies/rx-tasks#1]
As per Bintray it should be ```'io.ashdavies.rx:rx-tasks:1.1.1'``` (https://goo.gl/yhjRTu). Also, any reason to use minSdk 19 (https://goo.gl/3c5hec)? It kind of makes no sense to me and can be perfectly lowered to 14 or 15 for example.

**Comment by ashdavies** [comment]
Should be fixed in `1.1.2`
