### ISSUE TITLE
Task<T> extension functions are not available outside of module

### ISSUE THREAD

**Issue by tbsandee** [ashdavies/rx-tasks#12]
Because the `SingleTaskOnSubscribe` and `CompletableTaskOnSubscribe` are `internal`, it prevents the extension functions in `TaskExtensions` from being available outside of the module. This, at least, on Kotlin 1.2.21.

Implementing the extensions instead using the public `RxTasks` functions resolves the issue.

**Comment by tbsandee** [comment]
```
fun Task<Void>.toCompletable(): Completable = RxTasks.completable(this)
fun <T> Task<T>.toSingle(): Single<T> = RxTasks.single(this)
```

**Comment by tbsandee** [comment]
I see now that the `RxTasks` functions are actually implemented using the extension functions, so obviously the code above won't work because it's a recursive loop. 

It did work to paste the above code into a .kt file in my project, however.

**Comment by ashdavies** [comment]
Aah I see, it might have been a previous version, I wouldn't want to expose `*TaskOnSubscribe` though, at least the original `RxTasks` methods are accessible for now

**Comment by tbsandee** [comment]
It's not an old version, it's the current version (2.0.0) and to be clear, the only way to use the extension functions in my project was to create a copy of them directly. As it stands, the only public API available is the RxTasks object.

If you don't want to expose the subscribe classes, then reverse the implementation. RxTasks object functions references the subscribe classes and the extension functions reference RxTasks functions. The extension functions can be marked inline to remove that small bit of overhead, if desired.

If you'd like I can submit a PR.

**Comment by tbsandee** [comment]
PR #15

**Comment by tbsandee** [comment]
mea culpa, see https://github.com/ashdavies/rx-tasks/issues/11#issuecomment-364523579
