### ISSUE TITLE
Feature Request: Allow scheduler to be supplied for receiving task results

### ISSUE THREAD

**Issue by tbsandee** [ashdavies/rx-tasks#14]
Currently the task results are always delivered on the main thread, which is okay. It's easy enough to switch back off using `observeOn`, but it would be nice to be able to optionally avoid this thread jump if you know you're going right back onto the IO or computation scheduler to process results.

I can submit a PR for this if you like. I was thinking overloads of RxTasks (and corresponding extensions for Kotlin).

**Comment by ashdavies** [comment]
I'm not sure I follow you, I intentionally avoided any thread changing in the library as to leave the choice to the consumer

**Comment by tbsandee** [comment]
You're correct, there is no thread switching in RxTasks but the Task is doing it automatically. 

For example, the success listener is registered using this API:

https://developers.google.com/android/reference/com/google/android/gms/tasks/Task.html#addOnSuccessListener(com.google.android.gms.tasks.OnSuccessListener<? super TResult>)

The documentation says (and I've verified through testing) that "The listener will be called on the main application thread." This means that the subsequent calls through emitter.onNext() will stay on the main thread. 

For my case I don't want to bother the main thread at all until I'm fully done with my flow. `subscribeOn` typically is used for this, but that only changes where the listeners are registered. `observeOn` can be used to move the flow back to the computation thread (for example) but you still context switch onto main thread briefly, which is unnecessary.
 
So instead, use 'public abstract Task<TResult> addOnSuccessListener (Executor executor, OnSuccessListener<? super TResult> listener)' to put the success result on a thread of our choice and move to main thread at last minute.

**Comment by tbsandee** [comment]
PR #16 for example, created for a project I'm working on.
