### ISSUE TITLE
Compile statement incorrect

### ISSUE THREAD

**Issue by athornz** [ashdavies/rx-tasks#2]
Hey Ash the compile statement in the readme is wrong - it should be:

`compile 'io.ashdavies.rx:rx-tasks:1.1.3'`

**Comment by ashdavies** [comment]
Hey @athornz thanks for pointing that out, I'll try and get round to updating it this week, alternatively you're welcome to open a PR 😉

**Comment by ashdavies** [comment]
fixed by #4
