### ISSUE TITLE
Can't seem to access v2.1.0

### ISSUE THREAD

**Issue by cstarner** [ashdavies/rx-tasks#21]
I have tried including the new version of this library in my project, but it cannot be resolved. Version 2.0.0 can be found just fine.

Doing a little poking around, it doesn't appear that 2.1.0 has been made available via Maven, nor has the Maven metadata been updated. Perhaps I'm wrong, and am missing something?

**Comment by ashdavies** [comment]
You're not missing anything, I was making some changes to the deployment configuration, which resulted in the artefacts not being uploaded, I'll be removing that release and resolve the upload issue shortly.

**Comment by athornz** [comment]
Hi,

What's the status of these releases? I can't seem to resolve anything above 2.0.0

**Comment by ashdavies** [comment]
I'm still working on the deployment configuration at the moment, apologies for the delay

**Comment by riclage** [comment]
@ashdavies Any update on this? Can we help?

**Comment by ashdavies** [comment]
@riclage at the moment I need to resolve the GPG signing in the build chain, just I've been pretty with work commitments as of late

**Comment by ashdavies** [comment]
Sorry for the delay, I've been busy on other projects, `2.1.2` should be available via [https://search.maven.org/artifact/io.ashdavies.rx.rxtasks/rx-tasks/2.1.2/aar](Maven Central)
