### ISSUE TITLE
Null values

### ISSUE THREAD

**Issue by athornz** [ashdavies/rx-tasks#3]
I've come across an issue using the fusedlocationprovider task with this library - it can emit null values. 

I think the only way around this would be to wrap null values with some kind of optional in the library?

**Comment by ashdavies** [comment]
Ah, Rx2 doesn't allow null emissions, emitting optionals would be an option, but I'd have to include a back port, perhaps instead catch null and emit it as an error instead

**Comment by athornz** [comment]
Or perhaps using a Maybe rather than Single would work?

**Comment by ashdavies** [comment]
Not a bad idea, but I'd wonder if that would result in unexpected behaviour in consumer applications due to an "expected" null  emission

**Comment by ashdavies** [comment]
I've opted to catch the NPE and emit an `onError` event, should be live with the next version
